### ISSUE TITLE
Travis builds should fail when scss-lint errors

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#374]
**Expected behavior:** When your styles fail the scss-linter, the build should fail in Travis.

**Actual behavior:** When your styles fail the scss-linter, the Travis build still passes.

**Steps to reproduce:** Branch, add some styles that don't pass the scss-linter, push your branch, and open a pull request to view the Travis build info.

You can paste the following style declaration into any stylesheet to produce scss-lint errors:

```scss
div#urmom > div.something.something span.wutwut + b.supdawg {
  width:100%;
  display:inline; 
  position:absolute; 
  color:rgba(0, 0, 0, 0.10)
}
```

I *think* if we can get the scss-lint to fail the ember build, that should produce the expected behavior in Travis, too. The whole point is to help enforce use of the linter and scaling our SCSS well.

-

cc @jkleinsc
